import 'dart:ui';

import 'package:dusty_dust/model/status_model.dart';
import 'package:flutter/material.dart';

final statusLevel = [
  StatusModel(
    level: 0,
    label: '최고',
    primaryColor: Color(0xFF2196D3),
    darkColor: Color(0xFF0069C0),
    lightColor: Color(0xFF6ec6FF),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/best.png',
    comment: '100년에 한 번 오는 날',
    minFineDust: 0,
    minUltraFineDust: 0,
    minO3: 0,
    minNo2: 0,
    minCO: 0,
    minSO2: 0,
  ),
  StatusModel(
    level: 1,
    label: '좋음',
    primaryColor: Color(0xFF03a9f4),
    darkColor: Color(0xFF007ac1),
    lightColor: Color(0xFF67daff),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/good.png',
    comment: '외부활동을 하기에 적절합니다',
    minFineDust: 16,
    minUltraFineDust: 9,
    minO3: 0.02,
    minNo2: 0.02,
    minCO: 1,
    minSO2: 0.01,
  ),
  StatusModel(
    level: 2,
    label: '양호',
    primaryColor: Color(0xFF00bcd4),
    darkColor: Color(0xFF008ba3),
    lightColor: Color(0xFF62efff),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/ok.png',
    comment: '공긱가 적당합니다',
    minFineDust: 31,
    minUltraFineDust: 16,
    minO3: 0.03,
    minNo2: 0.03,
    minCO: 2,
    minSO2: 0.02,
  ),
  StatusModel(
    level: 3,
    label: '보통',
    primaryColor: Color(0xFF009688),
    darkColor: Color(0xFF00675b),
    lightColor: Color(0xFF52c7b8),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/mediocre.png',
    comment: '살아갈 수 있어요',
    minFineDust: 41,
    minUltraFineDust: 21,
    minO3: 0.06,
    minNo2: 0.05,
    minCO: 5.5,
    minSO2: 0.04,
  ),
  StatusModel(
    level: 4,
    label: '나쁨',
    primaryColor: Color(0xFFffc107),
    darkColor: Color(0xFFc79100),
    lightColor: Color(0xFFfff350),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/bad.png',
    comment: '별로에요',
    minFineDust: 51,
    minUltraFineDust: 26,
    minO3: 0.09,
    minNo2: 0.06,
    minCO: 9,
    minSO2: 0.05,
  ),
  StatusModel(
    level: 5,
    label: '상당히나쁨',
    primaryColor: Color(0xFFff9800),
    darkColor: Color(0xFFc66900),
    lightColor: Color(0xFFffc947),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/very_bad.png',
    comment: '외출을 자제해주세요',
    minFineDust: 76,
    minUltraFineDust: 38,
    minO3: 0.12,
    minNo2: 0.13,
    minCO: 12,
    minSO2: 0.1,
  ),
  StatusModel(
    level: 6,
    label: '매우나쁨',
    primaryColor: Color(0xFFf44336),
    darkColor: Color(0xFFba000d),
    lightColor: Color(0xFFff7961),
    detailFontColor: Colors.black,
    imagePtth: 'asset/img/worse.png',
    comment: '나가지 말아요',
    minFineDust: 101,
    minUltraFineDust: 62,
    minO3: 0.15,
    minNo2: 0.2,
    minCO: 15,
    minSO2: 0.15,
  ),
  StatusModel(
    level: 7,
    label: '최악',
    primaryColor: Color(0xFF12121),
    darkColor: Color(0xFF000000),
    lightColor: Color(0xFF484848),
    detailFontColor: Colors.white,
    imagePtth: 'asset/img/worst.png',
    comment: '살아갈 수 없어요',
    minFineDust: 151,
    minUltraFineDust: 76,
    minO3: 0.38,
    minNo2: 1.1,
    minCO: 32,
    minSO2: 0.16,
  ),
];
